FROM python:3.12-slim
WORKDIR /app
COPY shared /app/shared
COPY poller /app/poller
COPY requirements.poller.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-m", "poller.main"]