version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ../docker/env/data_service.env
    ports:
      - "5432:5432"
    volumes:
      - ../_storage/postgres_data:/var/lib/postgresql/data
    networks:
      - bot-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # HTTP management UI port
    volumes:
      - ../_storage/rabbitmq_data:/var/lib/rabbitmq
      - ../_storage/rabbitmq_log:/var/log/rabbitmq
    networks:
      - bot-net
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../_storage/redis_data:/data
    networks:
      - bot-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - bot-net

  poller:
    image: poller-image
    build:
      context: ..
      dockerfile: docker/Dockerfile.poller
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - bot-net
    env_file:
      - ../docker/env/tgclient.env
      - ../docker/env/broker_docker.env

  web:
    image: web-image
    build:
      context: ..
      dockerfile: docker/Dockerfile.dataservice
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bot-net
    env_file:
      - ../docker/env/data_service_docker.env

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
  redis_data:

networks:
  bot-net:
    driver: bridge